### Common
GET http://localhost:8000/ready HTTP/1.1

###

POST http://localhost:8000/setParameter HTTP/1.1
content-type: application/json

{
    "port":"8080"
}

###
GET http://localhost:8000/setParameter?port=8080 HTTP/1.1

### Client

GET http://localhost:8000/getWrongTrace/123456 HTTP/1.1


### Backend
POST http://localhost:8002/setParameter HTTP/1.1
content-type: application/json

{
    "port":"8080"
}

###
POST http://localhost:8002/setWrongTraceId HTTP/1.1
content-type: application/json

{
    "id":"654321"
}
