// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.14.0
// source: protofiles/trace.proto

// import "google/protobuf/empty.proto";

package trace

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type PayloadMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Action  string   `protobuf:"bytes,1,opt,name=Action,proto3" json:"Action,omitempty"`
	ID      string   `protobuf:"bytes,2,opt,name=ID,proto3" json:"ID,omitempty"`
	Records []string `protobuf:"bytes,3,rep,name=Records,proto3" json:"Records,omitempty"`
}

func (x *PayloadMessage) Reset() {
	*x = PayloadMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protofiles_trace_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PayloadMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayloadMessage) ProtoMessage() {}

func (x *PayloadMessage) ProtoReflect() protoreflect.Message {
	mi := &file_protofiles_trace_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayloadMessage.ProtoReflect.Descriptor instead.
func (*PayloadMessage) Descriptor() ([]byte, []int) {
	return file_protofiles_trace_proto_rawDescGZIP(), []int{0}
}

func (x *PayloadMessage) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *PayloadMessage) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *PayloadMessage) GetRecords() []string {
	if x != nil {
		return x.Records
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Body string `protobuf:"bytes,1,opt,name=Body,proto3" json:"Body,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protofiles_trace_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_protofiles_trace_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_protofiles_trace_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

var File_protofiles_trace_proto protoreflect.FileDescriptor

var file_protofiles_trace_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x2f, 0x74, 0x72, 0x61,
	0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x74, 0x72, 0x61, 0x63, 0x65, 0x22,
	0x52, 0x0a, 0x0e, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x52, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x52, 0x65, 0x63, 0x6f,
	0x72, 0x64, 0x73, 0x22, 0x1e, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x42, 0x6f, 0x64, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x42,
	0x6f, 0x64, 0x79, 0x32, 0x8c, 0x01, 0x0a, 0x0c, 0x54, 0x72, 0x61, 0x63, 0x65, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x3b, 0x0a, 0x0f, 0x53, 0x65, 0x74, 0x57, 0x72, 0x6f, 0x6e, 0x67,
	0x54, 0x72, 0x61, 0x63, 0x65, 0x49, 0x44, 0x12, 0x15, 0x2e, 0x74, 0x72, 0x61, 0x63, 0x65, 0x2e,
	0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x0f,
	0x2e, 0x74, 0x72, 0x61, 0x63, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x3f, 0x0a, 0x0d, 0x46, 0x69, 0x6e, 0x64, 0x54, 0x72, 0x61, 0x63, 0x65, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x15, 0x2e, 0x74, 0x72, 0x61, 0x63, 0x65, 0x2e, 0x50, 0x61, 0x79, 0x6c, 0x6f,
	0x61, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x15, 0x2e, 0x74, 0x72, 0x61, 0x63,
	0x65, 0x2e, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x22, 0x00, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x3b, 0x74, 0x72, 0x61, 0x63, 0x65, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protofiles_trace_proto_rawDescOnce sync.Once
	file_protofiles_trace_proto_rawDescData = file_protofiles_trace_proto_rawDesc
)

func file_protofiles_trace_proto_rawDescGZIP() []byte {
	file_protofiles_trace_proto_rawDescOnce.Do(func() {
		file_protofiles_trace_proto_rawDescData = protoimpl.X.CompressGZIP(file_protofiles_trace_proto_rawDescData)
	})
	return file_protofiles_trace_proto_rawDescData
}

var file_protofiles_trace_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protofiles_trace_proto_goTypes = []interface{}{
	(*PayloadMessage)(nil), // 0: trace.PayloadMessage
	(*Response)(nil),       // 1: trace.Response
}
var file_protofiles_trace_proto_depIdxs = []int32{
	0, // 0: trace.TraceService.SetWrongTraceID:input_type -> trace.PayloadMessage
	0, // 1: trace.TraceService.FindTraceInfo:input_type -> trace.PayloadMessage
	1, // 2: trace.TraceService.SetWrongTraceID:output_type -> trace.Response
	0, // 3: trace.TraceService.FindTraceInfo:output_type -> trace.PayloadMessage
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protofiles_trace_proto_init() }
func file_protofiles_trace_proto_init() {
	if File_protofiles_trace_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protofiles_trace_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PayloadMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protofiles_trace_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protofiles_trace_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protofiles_trace_proto_goTypes,
		DependencyIndexes: file_protofiles_trace_proto_depIdxs,
		MessageInfos:      file_protofiles_trace_proto_msgTypes,
	}.Build()
	File_protofiles_trace_proto = out.File
	file_protofiles_trace_proto_rawDesc = nil
	file_protofiles_trace_proto_goTypes = nil
	file_protofiles_trace_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// TraceServiceClient is the client API for TraceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TraceServiceClient interface {
	SetWrongTraceID(ctx context.Context, in *PayloadMessage, opts ...grpc.CallOption) (*Response, error)
	FindTraceInfo(ctx context.Context, in *PayloadMessage, opts ...grpc.CallOption) (*PayloadMessage, error)
}

type traceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTraceServiceClient(cc grpc.ClientConnInterface) TraceServiceClient {
	return &traceServiceClient{cc}
}

func (c *traceServiceClient) SetWrongTraceID(ctx context.Context, in *PayloadMessage, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/trace.TraceService/SetWrongTraceID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *traceServiceClient) FindTraceInfo(ctx context.Context, in *PayloadMessage, opts ...grpc.CallOption) (*PayloadMessage, error) {
	out := new(PayloadMessage)
	err := c.cc.Invoke(ctx, "/trace.TraceService/FindTraceInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TraceServiceServer is the server API for TraceService service.
type TraceServiceServer interface {
	SetWrongTraceID(context.Context, *PayloadMessage) (*Response, error)
	FindTraceInfo(context.Context, *PayloadMessage) (*PayloadMessage, error)
}

// UnimplementedTraceServiceServer can be embedded to have forward compatible implementations.
type UnimplementedTraceServiceServer struct {
}

func (*UnimplementedTraceServiceServer) SetWrongTraceID(context.Context, *PayloadMessage) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetWrongTraceID not implemented")
}
func (*UnimplementedTraceServiceServer) FindTraceInfo(context.Context, *PayloadMessage) (*PayloadMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindTraceInfo not implemented")
}

func RegisterTraceServiceServer(s *grpc.Server, srv TraceServiceServer) {
	s.RegisterService(&_TraceService_serviceDesc, srv)
}

func _TraceService_SetWrongTraceID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PayloadMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TraceServiceServer).SetWrongTraceID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/trace.TraceService/SetWrongTraceID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TraceServiceServer).SetWrongTraceID(ctx, req.(*PayloadMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _TraceService_FindTraceInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PayloadMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TraceServiceServer).FindTraceInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/trace.TraceService/FindTraceInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TraceServiceServer).FindTraceInfo(ctx, req.(*PayloadMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _TraceService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "trace.TraceService",
	HandlerType: (*TraceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetWrongTraceID",
			Handler:    _TraceService_SetWrongTraceID_Handler,
		},
		{
			MethodName: "FindTraceInfo",
			Handler:    _TraceService_FindTraceInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protofiles/trace.proto",
}
